import Head from 'next/head'
import Image from 'next/image'
import Avatar from '@/components/Avatar'
import {ViewfinderCircleIcon} from '@heroicons/react/20/solid' 
import Footer from '@/components/Footer'
import { FormEventHandler, useRef } from 'react'
import { useRouter } from 'next/router'
import SearchBar from '@/components/SearchBar'


export default function Home() {
  const router = useRouter()
  const ref = useRef<HTMLInputElement>(null)

  const search = (e : React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const value = ref.current.value

    if (!value) return;

    router.push(`/search?term=${value}`)
  }
  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className='flex w-full justify-between p-5 text-sm text-gray-700'>
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>
        
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>
        <ViewfinderCircleIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>

        <Avatar url={'https://i.ytimg.com/vi/xb2QmD4oEZY/maxresdefault.jpg'}/>
        </div>
      </header>
      {/* Body */}
      <div className="flex flex-col items-center flex-grow w-full">

        <Image
          src="https://1000marcas.net/wp-content/uploads/2020/02/logo-Google.png"
          alt="google logo"
          width={300}
          height={100}
        />
        <SearchBar/>
      {/* <form className="flex flex-col items-center flex-grow w-4/5" onSubmit={search}>
        <div className='flex w-full hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
          <MagnifyingGlassIcon className='mr-3 h-5 text-gray-500' />
          <input type="text" className='focus:outline-none flex-grow' ref={ref} />
          <MicrophoneIcon className='h-5 text-gray-500'/>
        </div>
        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-9 sm:space-y-0 sm:flex-row sm:space-x-4'>
          <button className='btn' type="submit">Google Search</button>

          <button className='btn'> I'm feeling lucky</button>
        </div>
      </form> */}
      </div>
      <Footer/>
    </div>
  )
}
